services:
  postgres:
    image: postgres:16
    container_name: dict-postgres
    environment:
      POSTGRES_DB: dictionary
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: apppass
    ports:
      - "5440:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dict-redis
    ports:
      - "6380:6379"

volumes:
  pgdata:
